; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps = 
	rei-vilo/PDLS_Basic@^10.1.0
	https://github.com/PervasiveDisplays/Pervasive_BWRY_Small.git#10.0.0
	wjtje/qr-code-generator-library@^1.7.0
